# Generated by Django 5.2.6 on 2026-01-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('facultad', 'nombre')},
        ),
        migrations.AddConstraint(
            model_name='opinion',
            constraint=models.UniqueConstraint(fields=('usuario', 'profesor'), name='unique_voto_por_profesor'),
        ),
        migrations.AddField(
            model_name='verificacionemail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
